// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: rpc/languageserver/LanguageServerState.proto

package languageserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanguageServerState_GetOpenDocuments_FullMethodName = "/languageserver.LanguageServerState/GetOpenDocuments"
)

// LanguageServerStateClient is the client API for LanguageServerState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanguageServerStateClient interface {
	GetOpenDocuments(ctx context.Context, in *GetOpenDocumentsRequest, opts ...grpc.CallOption) (*GetOpenDocumentsResponse, error)
}

type languageServerStateClient struct {
	cc grpc.ClientConnInterface
}

func NewLanguageServerStateClient(cc grpc.ClientConnInterface) LanguageServerStateClient {
	return &languageServerStateClient{cc}
}

func (c *languageServerStateClient) GetOpenDocuments(ctx context.Context, in *GetOpenDocumentsRequest, opts ...grpc.CallOption) (*GetOpenDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOpenDocumentsResponse)
	err := c.cc.Invoke(ctx, LanguageServerState_GetOpenDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanguageServerStateServer is the server API for LanguageServerState service.
// All implementations must embed UnimplementedLanguageServerStateServer
// for forward compatibility.
type LanguageServerStateServer interface {
	GetOpenDocuments(context.Context, *GetOpenDocumentsRequest) (*GetOpenDocumentsResponse, error)
	mustEmbedUnimplementedLanguageServerStateServer()
}

// UnimplementedLanguageServerStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanguageServerStateServer struct{}

func (UnimplementedLanguageServerStateServer) GetOpenDocuments(context.Context, *GetOpenDocumentsRequest) (*GetOpenDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpenDocuments not implemented")
}
func (UnimplementedLanguageServerStateServer) mustEmbedUnimplementedLanguageServerStateServer() {}
func (UnimplementedLanguageServerStateServer) testEmbeddedByValue()                             {}

// UnsafeLanguageServerStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanguageServerStateServer will
// result in compilation errors.
type UnsafeLanguageServerStateServer interface {
	mustEmbedUnimplementedLanguageServerStateServer()
}

func RegisterLanguageServerStateServer(s grpc.ServiceRegistrar, srv LanguageServerStateServer) {
	// If the following call pancis, it indicates UnimplementedLanguageServerStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanguageServerState_ServiceDesc, srv)
}

func _LanguageServerState_GetOpenDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanguageServerStateServer).GetOpenDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanguageServerState_GetOpenDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanguageServerStateServer).GetOpenDocuments(ctx, req.(*GetOpenDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanguageServerState_ServiceDesc is the grpc.ServiceDesc for LanguageServerState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanguageServerState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "languageserver.LanguageServerState",
	HandlerType: (*LanguageServerStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOpenDocuments",
			Handler:    _LanguageServerState_GetOpenDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/languageserver/LanguageServerState.proto",
}
